project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!code/"
    - "!data/"
    - "!output"

website:
  title: "smk-tutorial"
  navbar:
    right:
      - slides.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    background: "dark"
    search: true

format:
  html:
    theme: sandstone
    css: styles.css



